ci: Update testing workflow (#3)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,23 +18,31 @@ jobs:
 
       - name: Checkout this repository
         uses: actions/checkout@v3
-        with:
-          repository: ${{ github.repository }}
-          path: bleachbit-cleaners
 
-      - name: Checkout official bleachbit repository
-        uses: actions/checkout@v3
-        with:
-          path: bleachbit
-          repository: bleachbit/bleachbit
-        
       - name: Copy markup xsd
-        run: cp -v ./bleachbit/doc/cleaner_markup_language.xsd ./bleachbit-cleaners/Cleaners/cleaner_markup_language.xsd
+        run: curl -OJ https://raw.githubusercontent.com/bleachbit/bleachbit/v4.4.2/doc/cleaner_markup_language.xsd
 
       - name: Conduct XML Test
+        run: xmllint ./Cleaners/*.xml --schema cleaner_markup_language.xsd --noout
+
+      - name: Ensure no XML has the same cleaner.id
         run: |
-          for xml in $(ls -b *.xml)
-          do
-          xmllint $xml --schema cleaner_markup_language.xsd --noout
+          # ensure that no XML files in Cleaners directory have the same cleaner.id attribute as other files
+          for f in Cleaners/*.xml; do
+              x=$(xmllint --xpath "//cleaner/@id" $f)
+              # For the files that are not f, check if they have the same cleaner.id attribute
+
+              for g in Cleaners/*.xml; do
+                  if [ "$f" == "$g" ]; then
+                      # If the file is the same as f, skip it
+                      continue
+                  fi
+
+                  y=$(xmllint --xpath "//cleaner/@id" $g)
+                  if [ "$x" == "$y" ]; then
+                      echo "Error: $f and $g have the same cleaner.id attribute"
+                      exit 1
+                      fi
+              done
+              echo "$f cleaner.id attribute is unique"
           done
-        working-directory: ./bleachbit-cleaners/Cleaners
